In [7]:
import numpy as np

How to create an array

In [8]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [9]:
type(a) #nd means n dimentional array


numpy.ndarray

Basic operations of array


In [10]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [11]:
# Creating 2-D array

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [12]:
# Creatind 3-D array

a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
# Creating a 4-D array

a4 =np.array ([[[[1,2],[3,4]],
                [[5,6],[7,8]]],
               [[[9,10],[11,12]],
              [[13,14],[15,16]]]])

print(a4.shape)

(1, 2, 2, 2, 2)


In [14]:
print(a2.shape)
print(a3.shape) # two 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [15]:
print(a2.ndim)
print(a3.ndim)

2
3


In [16]:
print(a2.dtype)

int64


In [17]:
#creating single dimentional array by range

np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
np.random.randint(1,11,size=(3,3))

array([[8, 9, 5],
       [1, 1, 7],
       [7, 9, 9]], dtype=int32)

In [22]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]]) # 2-D array with 3 rows and 3 colums
y = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(x+y)
print(x-y)
print(x*y)

[[ 8  4  6]
 [ 6 10  8]
 [10 13 10]]
[[ 6  0  0]
 [-2  0 -4]
 [-4 -3 -8]]
[[ 7  4  9]
 [ 8 25 12]
 [21 40  9]]


In [24]:
print(x@y) # Matrix multiplication

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [25]:
np.dot(x,y)  # dot meathod is used for matrix multiplication

array([[36, 48, 60],
       [36, 45, 54],
       [30, 39, 48]])

In [26]:
np.prod(x) # prod meathod is used to multiply all the elements of a matrix and give total product of a matrix

np.int64(12600)

In [27]:
x.prod()  # product of all element in the array

np.int64(12600)

In [28]:
x.mean() # mean of all elements in the array

np.float64(3.3333333333333335)

In [29]:
y.mean()

np.float64(5.0)

In [30]:
x.mean(axis=0) # find the mean of each coloum when set axis at 0

array([4., 4., 2.])

In [31]:
y.mean(axis=1) # find the mean of each row when we set axis 1

array([2., 5., 8.])

In [32]:
print(x.sum()) # sum of all element in the array
print(x.var()) # cariance of all the element in the array
print(x.std()) # standard deviation of all the elements in the array

30
3.3333333333333335
1.8257418583505538


In [33]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a , 25)) # 25th percentile
print(np.percentile(a , 50)) # 50th percentile
print(np.percentile(a , 75)) # 75th percentile

3.0
5.0
7.0


In [34]:
b = np.array ([[59,29,93,93],
              [84,60,30,66],
              [60,63,38,20],
              [31,32,61,92]])
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [60 63 38 20]
 [31 32 61 92]]


In [35]:
print('2x8')
print(b.reshape(2,8))

2x8
[[59 29 93 93 84 60 30 66]
 [60 63 38 20 31 32 61 92]]


In [36]:
print('8x2')
print(b.reshape(8,2))

8x2
[[59 29]
 [93 93]
 [84 60]
 [30 66]
 [60 63]
 [38 20]
 [31 32]
 [61 92]]


In [37]:
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [60 63 38 20]
 [31 32 61 92]]
